import {fields,kindOf,filterRecords,matchesDuplicate,toCsv,importHeaders,importRecords} from './registry-tools.js';
export function createRegistryUI(ctx) {
  const {db,shell,esc,label,date,logo,navigate,refresh,flash,canEnter}=ctx;
  const state=ctx.state, phoneFields=ctx.phoneFields;
  let filters={search:'',kind:'',status:'',parish:'',from:'',to:''}, candidates=[];
  const parishName=r=>state().parishes.find(p=>p.id===r.parish_id)?.name||state().parish?.name||'Parish';
  const item=(name,value)=>`<div><small>${esc(name)}</small><strong>${esc(value||'—')}</strong></div>`;
  const openRecord=id=>{const record=state().records.find(r=>r.id===id);if(record)navigate('detail',record);};
  function download(name,text,type='text/csv;charset=utf-8') {const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function printPage(title,body) {
    let frame=document.querySelector('#print-frame');frame?.remove();frame=document.createElement('iframe');frame.id='print-frame';frame.title=title;frame.style.cssText='position:fixed;width:1px;height:1px;left:-10000px;border:0';document.body.append(frame);
    frame.onload=async()=>{await Promise.all([...frame.contentDocument.images].map(img=>img.complete?Promise.resolve():new Promise(resolve=>{img.onload=resolve;img.onerror=resolve;})));frame.contentWindow.focus();frame.contentWindow.print();};
    frame.srcdoc=`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>@page{size:A4;margin:18mm}body{font:14px Georgia,serif;color:#222}header{text-align:center;border-bottom:2px solid #68283a;padding-bottom:14px}header img{height:100px}h1{font-size:24px}h2{font-size:19px}table{border-collapse:collapse;width:100%}td,th{padding:8px;border:1px solid #ccc;text-align:left}dl{display:grid;grid-template-columns:40% 60%;gap:12px}dt{font-weight:bold}dd{margin:0;overflow-wrap:anywhere}.sign{display:flex;justify-content:space-between;margin-top:65px}.sign div{border-top:1px solid #222;padding-top:8px;min-width:160px}.note{font-size:12px;margin-top:25px;color:#555}tr{break-inside:avoid}</style></head><body>${body}</body></html>`;
  }
  const reportRows=rows=>[['Parish','Name','Sacrament','Date','Register no.','Volume','Status','Parents','Sponsors','Officiating clergy',...phoneFields.map(f=>f[1])],...rows.map(r=>[parishName(r),r.subject_name,label(kindOf(r.kind)),r.event_date,r.register_number,r.register_volume,r.status,r.details?.parents,r.details?.sponsors,r.details?.officiating_clergy,...phoneFields.map(([key])=>r.details?.[key])])];
  function list() {
    const {records,profile,parishes}=state();const pending=records.filter(r=>r.status==='pending').length;
    shell(`<header class="page-head"><div><p class="eyebrow">${profile.role==='diocese'?'DIOCESAN VIEW':'PARISH REGISTER'}</p><h1>Sacramental records</h1><p>${profile.role==='diocese'?'Approved records across parishes.':'Register entries and follow the parish priest’s approval.'}</p></div>${canEnter()?'<button id="add" class="primary">Add entry</button>':''}</header><section class="stats"><div><span>Total visible</span><strong>${records.length}</strong></div><div><span>Awaiting approval</span><strong>${pending}</strong></div><div><span>Approved</span><strong>${records.filter(r=>r.status==='approved').length}</strong></div></section><section class="panel"><div class="panel-head"><h2>Search the register</h2></div><div class="advanced-filters"><label>Search<input id="search" type="search" value="${esc(filters.search)}" placeholder="Name, parents, sponsors, register no."></label><label>Sacrament<select id="kind"><option value="">All sacraments</option>${Object.keys(fields).map(k=>`<option value="${k}">${label(k)}</option>`).join('')}</select></label><label>Status<select id="status"><option value="">All visible statuses</option>${['draft','pending','returned','approved'].map(k=>`<option>${k}</option>`).join('')}</select></label><label>Parish<select id="parish"><option value="">All visible parishes</option>${parishes.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><label>From<input id="from" type="date" value="${esc(filters.from)}"></label><label>To<input id="to" type="date" value="${esc(filters.to)}"></label></div><div class="actions toolbar"><button class="secondary" id="export">Download CSV</button><button class="secondary" id="print-register">Print filtered register</button><button class="secondary" id="report">Print summary report</button><span id="result-count"></span></div><div id="rows"></div></section>`);
    document.querySelector('#add')?.addEventListener('click',()=>navigate('form'));
    let found=[];
    const paint=()=>{for(const key of Object.keys(filters))filters[key]=document.getElementById(key).value;found=filterRecords(state().records,filters,parishes);document.querySelector('#result-count').textContent=`${found.length} matching entries`;
      document.querySelector('#rows').innerHTML=found.length?`<div class="table-wrap"><table><thead><tr><th>Parish</th><th>Name</th><th>Sacrament</th><th>Date</th><th>Register no.</th><th>Sponsors</th><th>Parents</th><th>Officiating clergy</th>${phoneFields.map(([,name])=>`<th>${name}</th>`).join('')}<th>Status</th><th></th></tr></thead><tbody>${found.map(r=>`<tr><td>${esc(parishName(r))}</td><td><strong>${esc(r.subject_name)}</strong></td><td>${label(kindOf(r.kind))}</td><td>${date(r.event_date)}</td><td>${esc(r.register_number||'—')}</td><td>${esc(r.details?.sponsors||'—')}</td><td>${esc(r.details?.parents||'—')}</td><td>${esc(r.details?.officiating_clergy||'—')}</td>${phoneFields.map(([key])=>`<td>${esc(r.details?.[key]||'—')}</td>`).join('')}<td><span class="badge ${r.status}">${label(r.status)}</span></td><td><button class="row-link" data-id="${r.id}">View</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No matching entries.</div>';document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openRecord(b.dataset.id));};
    for(const key of Object.keys(filters)){document.getElementById(key).value=filters[key];document.getElementById(key).addEventListener(key==='search'?'input':'change',paint);}paint();
    document.querySelector('#export').onclick=()=>download('sacrament-register.csv','\uFEFF'+toCsv(reportRows(found)));
    document.querySelector('#print-register').onclick=()=>printPage('Sacrament register',`<h1>Diocesan Sacrament Registry</h1><p>Filtered register · ${found.length} entries · Printed ${esc(new Date().toLocaleDateString('en-NG'))}</p><table>${reportRows(found).map((row,i)=>`<tr>${row.slice(0,7).map(cell=>`<${i?'td':'th'}>${esc(cell)}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</table>`);
    document.querySelector('#report').onclick=()=>{const groups=new Map();for(const r of found){const key=[parishName(r),kindOf(r.kind),r.event_date.slice(0,7),r.status].join('|');groups.set(key,(groups.get(key)||0)+1);}printPage('Sacrament summary',`<h1>Sacrament summary report</h1><p>From ${esc(filters.from||'earliest')} to ${esc(filters.to||'latest')} · ${found.length} visible entries</p><table><tr><th>Parish</th><th>Sacrament</th><th>Month</th><th>Status</th><th>Total</th></tr>${[...groups].sort().map(([key,n])=>`<tr>${[...key.split('|'),n].map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</table>`);};
  }
  function form() {
    shell(`<button class="back" id="back">← Registers</button><div class="form-head"><p class="eyebrow">PARISH ENTRY</p><h1>New sacramental entry</h1><p>Saved details require an administrator to correct. Check the entry before saving.</p></div><form id="entry" class="panel entry-form"><div class="form-grid"><label>Sacrament<select name="kind">${Object.keys(fields).map(k=>`<option>${k}</option>`).join('')}</select></label><label>Name of person / couple<input name="subject_name" required minlength="2" maxlength="240"></label><label>Date of sacrament<input name="event_date" type="date" required></label><label>Register number<input name="register_number" maxlength="80"></label><label>Register volume<input name="register_volume" maxlength="80"></label><label>Parents<input name="parents" maxlength="500"></label><label>Sponsors<input name="sponsors" maxlength="500"></label><label>Officiating clergy<input name="officiating_clergy" maxlength="240"></label></div><section><h2>Sacrament details</h2><div id="specific" class="form-grid"></div></section><label>Link to an existing person’s sacrament history<select name="person_link"><option value="">Create a new person history</option>${state().records.filter(r=>!['marriage','matrimony'].includes(r.kind)&&r.details?.person_id).map(r=>`<option value="${esc(r.details.person_id)}">${esc(r.subject_name)} · ${label(r.kind)} · ${date(r.event_date)}</option>`).join('')}</select></label><p class="hint" id="link-hint">Select only after verifying the person’s identity. Marriage records remain a couple record.</p><label>Additional details<textarea name="notes" rows="4" maxlength="5000"></textarea></label><div id="duplicates" role="status"></div><div class="actions"><button class="primary" type="submit">Check and save draft</button><span id="form-error" class="error" role="alert"></span></div></form>`);
    document.querySelector('#back').onclick=()=>navigate('list');
    const entry=document.querySelector('#entry');let values={};
    const specific=()=>{document.querySelectorAll('#specific input').forEach(i=>values[i.name]=i.value);const k=entry.elements.kind.value;
      document.querySelector('#specific').innerHTML=[...fields[k],...(k==='matrimony'?phoneFields:[])].map(([key,name,type='text'])=>`<label>${esc(name)}<input name="${key}" type="${key.endsWith('_phone')?'tel':type}" value="${esc(values[key])}" maxlength="${key.endsWith('_phone')?40:240}"></label>`).join('');entry.elements.person_link.disabled=k==='matrimony';};entry.elements.kind.onchange=specific;specific();
    entry.onsubmit=async e=>{e.preventDefault();const fd=new FormData(entry),button=entry.querySelector('[type=submit]'),errorBox=document.querySelector('#form-error');button.disabled=true;errorBox.textContent='';
      try{const kind=fd.get('kind');const details=Object.fromEntries(['parents','sponsors','officiating_clergy','notes',...fields[kind].map(f=>f[0]),...(kind==='matrimony'?phoneFields.map(f=>f[0]):[])].map(k=>[k,String(fd.get(k)||'').trim()]));details.person_id=kind==='matrimony'?crypto.randomUUID():fd.get('person_link')||crypto.randomUUID();
        if(kind==='matrimony'&&(!details.spouse_1_name||!details.spouse_2_name))throw Error('Enter both spouses’ names.');
        const record={kind,subject_name:String(fd.get('subject_name')).trim(),event_date:fd.get('event_date'),register_number:String(fd.get('register_number')).trim(),register_volume:String(fd.get('register_volume')).trim(),parish_id:state().profile.parish_id,details};
        const {data:duplicates,error}=await db.rpc('find_record_duplicates',{p_kind:kind,p_subject_name:record.subject_name,p_event_date:record.event_date,p_register_number:record.register_number,p_register_volume:record.register_volume});if(error)throw Error(error.message);
        if(duplicates?.length){document.querySelector('#duplicates').innerHTML='<div class="notice">A possible duplicate already exists. Open the register and check before creating another entry.</div>';throw Error('Duplicate entry detected. Ask the administrator to check it.');}
        const result=await save(record);if(result.error)throw Error(result.error.message);navigate('list');await refresh('Draft saved. Submit it when ready for the priest’s review.');
      }catch(error){errorBox.textContent=error.message;}finally{button.disabled=false;}
    };
  }
  function save(r){return db.rpc('save_record',{p_id:null,p_parish_id:r.parish_id,p_kind:r.kind,p_subject_name:r.subject_name,p_event_date:r.event_date,p_register_number:r.register_number,p_register_volume:r.register_volume,p_register_page:null,p_details:r.details});}
  async function detail() {
    const r=state().current,d=r.details||{};if(!r)return;const k=kindOf(r.kind);
    const linked=d.person_id?state().records.filter(other=>other.details?.person_id===d.person_id):[];
    shell(`<button class="back" id="back">← Registers</button><header class="page-head"><div><p class="eyebrow">${esc(parishName(r))} · ${label(k)}</p><h1>${esc(r.subject_name)}</h1><span class="badge ${r.status}">${label(r.status)}</span></div></header><section class="panel detail-grid">${[['Date',date(r.event_date)],['Register number',r.register_number],['Volume',r.register_volume],['Parents',d.parents],['Sponsors',d.sponsors],['Officiating clergy',d.officiating_clergy],...(fields[k]||[]).map(([key,name,type])=>[name,type==='date'?date(d[key]):d[key]]),...(k==='matrimony'?phoneFields.map(([key,name])=>[name,d[key]]):[])].map(([name,value])=>item(name,value)).join('')}</section><section class="panel notes"><h2>Additional details</h2><p>${esc(d.notes||'No additional details.')}</p><small>Person history ID: ${esc(d.person_id||'Not linked; administrator can assign a verified link.')}</small></section>${r.return_reason?`<div class="notice">Awaiting administrator correction: ${esc(r.return_reason)}</div>`:''}<div class="actions">${canEnter()&&['draft','returned'].includes(r.status)?'<button class="primary" id="submit">Submit for approval</button>':''}${state().profile.role==='priest'&&r.status==='pending'?'<button class="primary" id="approve">Approve entry</button><button class="secondary" id="return">Return for correction</button>':''}${r.status==='approved'&&canEnter()?'<button class="secondary" id="certificate">Print certificate</button>':''}</div><section class="panel notes"><h2>Linked sacrament history</h2>${linked.length?linked.map(other=>`<p><button class="row-link" data-linked="${other.id}">${label(kindOf(other.kind))} · ${date(other.event_date)} · ${esc(other.subject_name)}</button></p>`).join(''):'<p>No verified linked history yet.</p>'}</section><section class="panel notes"><h2>Record and correction history</h2><div id="history">Loading history…</div></section>`);
    document.querySelector('#back').onclick=()=>navigate('list');document.querySelectorAll('[data-linked]').forEach(b=>b.onclick=()=>openRecord(b.dataset.linked));
    const action=async(name,args,success)=>{const {error}=await db.rpc(name,args);if(error)return flash(error.message);navigate('list');await refresh(success);};
    document.querySelector('#submit')?.addEventListener('click',()=>action('submit_record',{p_id:r.id},'Sent to the parish priest.'));
    document.querySelector('#approve')?.addEventListener('click',()=>{if(confirm('Approve after checking the original parish register?'))action('review_record',{p_id:r.id,p_approve:true},'Entry approved.');});
    document.querySelector('#return')?.addEventListener('click',()=>{const reason=prompt('What needs correction by the server administrator?');if(reason===null)return;if(reason.trim().length<4)return flash('Please provide a clear reason.');action('review_record',{p_id:r.id,p_approve:false,p_reason:reason.trim()},'Returned for administrator correction.');});
    document.querySelector('#certificate')?.addEventListener('click',async()=>{const {data:latest,error}=await db.from('records').select('*').eq('id',r.id).single();if(error)return flash(error.message);if(latest?.status!=='approved')return flash('This record is no longer approved. Refresh and wait for the priest’s approval before printing.');certificate(latest);});
    const {data,error}=await db.from('record_events').select('*').eq('record_id',r.id).order('happened_at',{ascending:false});if(state().current?.id!==r.id||state().view!=='detail')return;
    document.querySelector('#history').innerHTML=error?`<p class="error">${esc(error.message)}</p>`:data.map(event=>{let changes='';if(event.previous_snapshot){const keys=['subject_name','event_date','kind','register_number','register_volume','details'];changes=keys.filter(key=>JSON.stringify(event.previous_snapshot[key])!==JSON.stringify(event.snapshot[key])).map(key=>`<li>${esc(key)}: ${esc(typeof event.previous_snapshot[key]==='object'?JSON.stringify(event.previous_snapshot[key]):event.previous_snapshot[key])} → ${esc(typeof event.snapshot[key]==='object'?JSON.stringify(event.snapshot[key]):event.snapshot[key])}</li>`).join('');}return `<article class="history-item"><strong>${esc(label(event.action))}</strong> · ${esc(new Date(event.happened_at).toLocaleString('en-NG'))}<p>${esc(event.admin_actor||event.actor_id||'Administrator')}${event.note?' · '+esc(event.note):''}</p>${changes?`<details><summary>View changes</summary><ul>${changes}</ul></details>`:''}</article>`;}).join('')||'<p>No events recorded.</p>';
  }
  function certificate(r) {
    if(r.status!=='approved'||!canEnter())return;const k=kindOf(r.kind),d=r.details||{};
    const rows=[['Name / couple',r.subject_name],['Date of sacrament',date(r.event_date)],['Register number',r.register_number],['Register volume',r.register_volume],['Parents',d.parents],['Sponsors',d.sponsors],['Officiating clergy',d.officiating_clergy],...(fields[k]||[]).filter(([key])=>d[key]).map(([key,name,type])=>[name,type==='date'?date(d[key]):d[key]])];
    printPage(`${label(k)} certificate`, `<header><img src="${logo}" alt="Diocesan logo"><h2>Catholic Diocese of Enugu</h2><h2>${esc(parishName(r))}</h2><h1>Certificate of ${label(k)}</h1></header><p>This is to certify that the following entry appears in the approved sacramental register of this parish.</p><dl>${rows.filter(([,value])=>value).map(([name,value])=>`<dt>${esc(name)}</dt><dd>${esc(value)}</dd>`).join('')}</dl><p class="note">Record reference: ${esc(r.id)}<br>Approved: ${esc(new Date(r.approved_at).toLocaleDateString('en-NG'))}<br>Printed: ${esc(new Date().toLocaleDateString('en-NG'))}</p><div class="sign"><div>Parish priest’s signature</div><div>Parish stamp / seal</div></div><p class="note">Valid when signed and stamped by the issuing parish. The parish must verify any required subsequent annotations before issue.</p>`);
  }
  function notifications() {
    const {records,profile}=state();const entries=records.filter(r=>(profile.role==='priest'&&r.status==='pending')||(['approved','returned'].includes(r.status)&&r.created_by===profile.user_id)).sort((a,b)=>b.updated_at.localeCompare(a.updated_at));
    shell(`<header class="page-head"><div><p class="eyebrow">STAFF UPDATES</p><h1>Approval notifications</h1><p>Updates refresh while this page is open. Open an entry to review its details.</p></div><button id="refresh-updates" class="secondary">Refresh now</button></header><section class="panel notes">${entries.map(r=>`<article class="history-item"><button class="row-link" data-id="${r.id}">${esc(r.subject_name)} · ${label(kindOf(r.kind))}</button><p>${r.status==='pending'?'Awaiting your approval':r.status==='returned'?'Returned for administrator correction':'Approved by the parish priest'} · ${esc(new Date(r.updated_at).toLocaleString('en-NG'))}</p></article>`).join('')||'<p>No approval updates.</p>'}</section>`);
    document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openRecord(b.dataset.id));document.querySelector('#refresh-updates').onclick=()=>refresh();
  }
  function imports() {
    if(!canEnter())return navigate('list');candidates=[];
    shell(`<header class="page-head"><div><p class="eyebrow">HISTORICAL REGISTERS</p><h1>Import records</h1><p>Download the template and enter dates as YYYY-MM-DD. Each imported record becomes a draft in your assigned parish.</p></div></header><section class="panel entry-form"><button id="template" class="secondary">Download CSV template</button><label>Choose CSV file<input id="csv-file" type="file" accept=".csv,text/csv"></label><p>Preview and check the records before importing. Up to 200 records per file. Existing duplicates are skipped.</p><div id="import-preview"></div><button id="import-save" class="primary" disabled>Import as drafts</button><progress id="import-progress" max="1" value="0"></progress><p id="import-status" role="status"></p></section>`);
    document.querySelector('#template').onclick=()=>download('sacrament-import-template.csv',toCsv([importHeaders]));
    const button=document.querySelector('#import-save'),status=document.querySelector('#import-status');
    document.querySelector('#csv-file').onchange=async e=>{button.disabled=true;candidates=[];try{const file=e.target.files[0];if(!file)return;if(file.size>2*1024*1024)throw Error('Choose a CSV file under 2 MB.');candidates=importRecords(await file.text(),state().profile.parish_id);document.querySelector('#import-preview').innerHTML=`<p>${candidates.length} records ready to check.</p><div class="table-wrap"><table><tr><th>Name</th><th>Sacrament</th><th>Date</th><th>Details</th></tr>${candidates.map(r=>`<tr><td>${esc(r.subject_name)}</td><td>${label(r.kind)}</td><td>${date(r.event_date)}</td><td>${esc(JSON.stringify(r.details))}</td></tr>`).join('')}</table></div>`;button.disabled=false;status.textContent='';}catch(error){status.textContent=error.message;}};
    button.onclick=async()=>{if(!confirm(`Import ${candidates.length} checked entries as drafts? They will still require the priest’s approval.`))return;button.disabled=true;document.querySelector('#csv-file').disabled=true;let saved=0,skipped=0;const failed=[];const progress=document.querySelector('#import-progress');progress.max=candidates.length;
      for(let i=0;i<candidates.length;i++){const record=candidates[i];status.textContent=`Processing ${i+1} of ${candidates.length}…`;if(state().records.some(r=>matchesDuplicate(r,record))){skipped++;}else{const result=await save({...record,details:{...record.details,person_id:record.details.person_id||crypto.randomUUID(),import_source:'historical_csv'}});if(result.error){if(result.error.message.includes('Duplicate'))skipped++;else failed.push({row:i+2,error:result.error.message});}else saved++;}progress.value=i+1;}
      status.textContent=`Finished: ${saved} drafts saved, ${skipped} duplicates skipped, ${failed.length} failed.${failed.length?' Failed rows: '+failed.map(f=>`${f.row} (${f.error})`).join('; '):''}`;document.querySelector('#csv-file').disabled=false;candidates=[];await refresh(undefined,false);
    };
  }
  return {list,form,detail,notifications,imports};
}
